name: lint-free

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # repeat same job for each subsystem
        subdir: [web-app, machine_learning_client]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        if: ${{ matrix.subdir == 'machine_learning_client' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev python3-dev ffmpeg

      - name: Install Pipenv and dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          PYTHONPATH=.. pipenv run pylint --disable=import-error --ignore=pyaudio.py **/*.py

      - name: Format with black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv run black --diff --check .
