name: ML Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "machine_learning_client/**"
      - ".github/workflows/ml-client.yml"

jobs:
  test:
    name: Test ML Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install system dependencies (for PyAudio + ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev libasound2-dev libportaudio2 libportaudiocpp0 ffmpeg

      - name: Install Pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd machine_learning_client
          pipenv install --dev
          # Uninstall any torch that got installed (CUDA build)
          pipenv run pip uninstall -y torch
          # Install torch 2.6.0 (CPU only on your platform)
          pipenv run pip install torch==2.6.0

      - name: Run tests and collect coverage
        env:
          CUDA_VISIBLE_DEVICES: "-1"
          TORCH_CUDA_DISABLE: "1"
          CFLAGS: "-I/usr/include -I/usr/local/include"
        run: |
          cd machine_learning_client
          PYTHONPATH=. pipenv run pytest tests/ --cov=machine_learning_client --cov-report=term-missing
