name: Web App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "web-app/**"
      - ".github/workflows/web-app.yml"

jobs:
  test:
    name: Test Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies (for PyAudio + ffmpeg + whisper)
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev libasound2-dev python3-dev ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd web-app
          pipenv install --dev

      - name: Run tests with pytest
        run: |
          cd web-app
          PYTHONPATH=. pipenv run pytest tests/
